root: true
env:
  node: true
  es6: true
extends:
  - airbnb-base
plugins:
  - import
rules:
  no-console: off
  import/extensions: off
  quotes:
    - "error"
    - "double"
  indent:
    - "error"
    - 4